pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'sh project-backend-setup.sh'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 hms/manage.py test hms/'
                sh 'echo Testing by philip'
            }
        }
    }
}
