pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'pip3 install hms/requirements.txt'
                sh 'echo Building'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 hms/hms/manage.py test'
                sh 'echo Testing by philip'
            }
        }
    }
}