# Generated by Django 3.2.9 on 2022-03-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0003_auto_20220309_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='pictures'),
        ),
    ]
